### PR TITLE
paging and keyword search in admin portlets, closes #81

### LINKED ISSUE #81: paging @ admin portlets
all admin portlets with lists should get a paging like the component list portlet

### PR DESCRIPTION
**Pull request by sw360-green-developer**

### CODE REVIEW

**Comment by mcjaeger** [comment]
looks good in gneral, just one thing: bulk release edit seems to crash (portlet not available) when there is no component / release at all. Stacktrace:

`
12:59:39,877 ERROR [http-bio-8080-exec-5][PortletRequestDispatcherImpl:115] org.apache.jasper.JasperException: An exception occurred processing JSP page /html/admin/bulkReleaseEdit/view.jsp at line 26__23: <portlet:defineObjects/>_24: <liferay-theme:defineObjects/>_25: _26: <jsp:useBean id="releaseList" type="java.util.List<com.siemens.sw360.datahandler.thrift.components.Release>"_27:              scope="request"/>_28: _29: <%--TODO--%>___Stacktrace: [Sanitized]
org.apache.jasper.JasperException: An exception occurred processing JSP page /html/admin/bulkReleaseEdit/view.jsp at line 26__23: <portlet:defineObjects/>_24: <liferay-theme:defineObjects/>_25: _26: <jsp:useBean id="releaseList" type="java.util.List<com.siemens.sw360.datahandler.thrift.components.Release>"_27:              scope="request"/>_28: _29: <%--TODO--%>___Stacktrace: [Sanitized]
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:575)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:462)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

...

Mar 02, 2016 12:59:39 PM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet bulkReleaseEdit Servlet threw exception
java.lang.InstantiationException: bean releaseList not found within scope
	at org.apache.jsp.html.admin.bulkReleaseEdit.view_jsp._jspService(view_jsp.java:236)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper
`

**Comment by sw360-green-developer** [comment]
This only happens if you try to load the Bulk Release Edit page as the setup admin user, because this user is not a proper SW360 user - it has no department, therefore the assertion in SW360Assert.java:60 fails.
`assertNotEmpty(user.getDepartment(), "User Department was empty in " + user.toString());`
If you load the page as a normal admin, an empty table is displayed just fine.
The problem applies just as much to the current master as to this branch, but I don't think it needs fixing. The setup admin is not supposed to administrate SW360 application, I believe.

@mcjaeger, let me know if you think it's worth fixing nevertheless.

**Comment by sw360-green-developer** [comment]
Fixed the display problem for consistency with other portlets. See also #109.

**Comment by sw360-blue-developer** [comment]
on the bulk release edit seems to be a problem with the width of the table.
a scrollbar is shown on each size of the window:
bildschirmfoto vom 2016-03-08 10 13 18

**Comment by sw360-green-developer** [comment]
can you retest, please?

**Comment by sw360-blue-developer** [comment]
new issue #117 created

**Pull request merged**
