### PR TITLE
Make the problem area a little bit nicer.

### PR DESCRIPTION
**Pull request by AngelM1981**

### CODE REVIEW

**Comment by maximilianhuber** [comment]
Hi, it might be better to create a PR from `AngelM1981:AngelM1981-patch-1` to `siemens:master`. This would remove the unnecessary merge commit.

**Comment by AngelM1981** [comment]
I think I already deleted this branch.

Maximilian Huber <notifications@github.com> schrieb am Di., 9. Feb. 2016
16:12:

**Comment by maximilianhuber** [comment]
You might be able to restore it on the page https://github.com/AngelM1981/sw360portal/pull/1. Alternatively you could squash the commits or create a new branch.

**Comment by AngelM1981** [comment]
Pull request will be send from patch branch.

**Pull request closed without merging**
