### PR TITLE
licenseExporter enriched with licenseType

### LINKED ISSUE #90: improve licenseType in LicenseExport

### PR DESCRIPTION
**Pull request by heydenreich**
closes #90

### CODE REVIEW

**Comment by maximilianhuber** [comment]
Code looks good

**Comment by mcjaeger** [comment]
hi, imported a license set from the previously running instance ... is this OK / should this work, because it does not allow to view the license detail:

`2016-02-25 16:18:16 ERROR ProcessFunction:41 - Internal error processing getByIDWithOwnModerationRequests
 SW360Exception(why:Invalid empty input!)
	at com.siemens.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:113)
	at com.siemens.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:107)
	at com.siemens.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:70)
	at com.siemens.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:65)
	at com.siemens.sw360.licenses.LicenseHandler.getByIDWithOwnModerationRequests(LicenseHandler.java:197)
	at com.siemens.sw360.datahandler.thrift.licenses.LicenseService$Processor$getByIDWithOwnModerationRequests.getResult(LicenseService.java:2225)
	at com.siemens.sw360.datahandler.thrift.licenses.LicenseService$Processor$getByIDWithOwnModerationRequests.getResult(LicenseService.java:2210)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
2016-02-25 16:18:16,422 ERROR LicensesPortlet:130 - Error fetching license details from backend
 org.apache.thrift.TApplicationException: Internal error processing getByIDWithOwnModerationRequests
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at com.siemens.sw360.datahandler.thrift.licenses.LicenseService$Client.recv_getByIDWithOwnModerationRequests(LicenseService.java:290)
	at com.siemens.sw360.datahandler.thrift.licenses.LicenseService$Client.getByIDWithOwnModerationRequests(LicenseService.java:275)
	at com.siemens.sw360.portal.portlets.licenses.LicensesPortlet.doView(LicensesPortlet.java:99)
	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:235)
	at com.liferay.util.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:314)
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:262)
	at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:103)
Feb 25, 2016 4:18:16 PM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet jsp threw exception
java.lang.InstantiationException: bean added_todos_from_moderation_request not found within scope`

**Comment by heydenreich** [comment]
Hi,

I've  tried it again:
1. build the licenseExporter branch
2. log in as as admin@sw360.org
3. export the licenses already in the database with the admin-export
licenses function -> LicensesBackup.lics
4. import LicensesBackup.lics with admin-import function
5. view details -> no problem
6. export licenses as csv -> no problem + licenseType displayed properly

This also works if I try a license with a pending moderation request. Then
also the "added_todos_..." are displayed properly.

Which user did you try? Do you have an old moderation request pending?


-- 
Dr. Birgit Heydenreich * birgit.heydenreich@tngtech.com * +49-174-3410216
TNG Technology Consulting GmbH, Betastr. 13a, 85774 Unterföhring
Geschäftsführer: Henrik Klagges, Christoph Stock, Dr. Robert Dahlke
Sitz: Unterföhring * Amtsgericht München * HRB 135082

Am 25.02.2016 um 21:46 schrieb Michael:

**Comment by mcjaeger** [comment]
clean vagrant with ./sw360-install.sh

**Comment by mcjaeger** [comment]
I am sorry, but neither with the exported license set (*.lics file) nor the one copied on Monday it works, instead:

Mar 01, 2016 9:34:04 PM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet componentImport Servlet threw exception
org.apache.thrift.TApplicationException: getRiskCategories failed: unknown result

-> portlet not available during import. 

done with newly generated box and vagrant deployment.

**Comment by heydenreich** [comment]
I tried it again with a fresh vagrant box. Deployed licenseExporter branch
and imported and exported licenses. Everything works fine. => ??
Shall we have a look together later?

-- 
Dr. Birgit Heydenreich * birgit.heydenreich@tngtech.com * +49-174-3410216
TNG Technology Consulting GmbH, Betastr. 13a, 85774 Unterföhring
Geschäftsführer: Henrik Klagges, Christoph Stock, Dr. Robert Dahlke
Sitz: Unterföhring * Amtsgericht München * HRB 135082

Am 01.03.2016 um 22:37 schrieb Michael:

**Comment by mcjaeger** [comment]
"kaum mahct man es richtig läuft es" - tested and couldbe merged from my testing trials.

**Pull request merged**
